### ISSUE TITLE
SHOWSTOPPER wallet issues..

### ISSUE THREAD

**Issue by cozmosnft** [tokenocean/cozmos#12]
Juan_teruel account couldn't send any tokens, even btc we backed up the wallet again and it seems to have fixed the problem/

![WhatsApp Image 2022-05-02 at 2 01 28 PM (1)](https://user-images.githubusercontent.com/103065410/166327292-d4d4579d-5f8c-470f-a83c-adccfbf0f9a1.jpeg)
![WhatsApp Image 2022-05-02 at 2 01 28 PM](https://user-images.githubusercontent.com/103065410/166327296-fdef33db-5cf3-4b36-9382-56e5565ec6ef.jpeg)

**Comment by asoltys** [comment]
I think this is fixed now
