### ISSUE TITLE
ACCEPT OFFER BUTTON/EMAILS not a show stopper

### ISSUE THREAD

**Issue by cozmosnft** [tokenocean/cozmos#14]
When you have an offer, you don't get any email notification or any kind ,, we thought that maybe meanwhile we work on the email notification, we could see a bigger button when there's an offer?

![87b74e58-6075-4344-ae4b-2c07e2dcbcec](https://user-images.githubusercontent.com/103065410/166513992-c1d92413-c516-4e8f-95f4-b12173a1c347.jpg)
?

**Comment by secondl1ght** [comment]
Added, pushing to staging now.
