### ISSUE TITLE
set price button instead of edit..  not a show stopper

### ISSUE THREAD

**Issue by cozmosnft** [tokenocean/cozmos#15]
text changes
![WhatsApp Image 2022-05-03 at 12 20 41 AM (1)](https://user-images.githubusercontent.com/103065410/166515066-a42d04f4-9785-4199-a668-069e035b0fe0.jpeg)
![WhatsApp Image 2022-05-03 at 11 03 46 AM](https://user-images.githubusercontent.com/103065410/166515115-1079b300-ab23-4238-acdd-5e639a7a1e67.jpeg)

**Comment by secondl1ght** [comment]
Done, pushing to staging now.
