### ISSUE TITLE
Error creating bids

### ISSUE THREAD

**Issue by cozmosnft** [tokenocean/cozmos#20]
There's a problem creating bids there's the error "NUMBER OF ATTEMPS Exceeded" then it creates corrupt ones..
i backed up my wallet and signed in and out... weird coz i did create 2 before with no issues... not sure if is my wallet that is corrupted.
even though i sent funds from my wallet to Juan's and it did work.. im adding screenshots of different errors..
you can see the files are corrupted and the fees have been taken from my wallet... 

![corrupted bids](https://user-images.githubusercontent.com/103065410/166875685-11328c5d-6d8b-422f-a380-aa41084f346d.JPG)
![error adding output 3h to end 3%royalty](https://user-images.githubusercontent.com/103065410/166875691-b7186a44-378c-4d99-b8da-f48432a6d2b1.JPG)
![error adding output 2 hours for bid to end](https://user-images.githubusercontent.com/103065410/166875700-c82b3924-b84d-427e-95ab-3216445e96b5.JPG)
![transactions 2](https://user-images.githubusercontent.com/103065410/166875825-1edfa98f-85ce-489f-aa97-5e0e2b2d5090.JPG)
![transactions](https://user-images.githubusercontent.com/103065410/166875828-c71b31ed-dc58-4c82-a22c-e55b7f5691e9.JPG)
![cosole bid input](https://user-images.githubusercontent.com/103065410/166875876-9ba0d9c2-fa21-41e4-b67b-e9a3e3465caf.JPG)
.

**Comment by asoltys** [comment]
Couldn't reproduce
