### ISSUE TITLE
ERROR WITH @SERGITOS ACCOUNT URGENT

### ISSUE THREAD

**Issue by cozmosnft** [tokenocean/cozmos#21]
I HAVE SWITCHED WALLETS AND THE ERROR IS DEFENITELY WITH THE ACCOUNT. JUAN CAN UPLOAD STUFF AND I CANT.. THEY ALL GET CORRUPTED "ERROR ADDING OUTPUT' AND 'INSUFICIENT FUNDS'
![ERROR ADDING OUTPUT](https://user-images.githubusercontent.com/103065410/166877372-96b32c81-169d-4c68-a7ae-8af32780960a.JPG)
![COSOLE SERGITOS WALLET ERROR](https://user-images.githubusercontent.com/103065410/166877552-c157ef38-0814-42db-b810-be2449a11f38.JPG)

**Comment by asoltys** [comment]
Couldn't reproduce, maybe try using a new account
