### ISSUE TITLE
PROBLEM WITH BIDS... show stopper

### ISSUE THREAD

**Issue by cozmosnft** [tokenocean/cozmos#22]
THERE IS DEFENITELY A PROBLEM WITH THE BIDS.... 1SCREEN IS MY PROFILE AND THE BIDS GET CROSSED... 2ND IMAGE IS  JUANS PROFILE WITH NO HISTORY ON THEM WHATSOEVER
3RD PICTURE IS MY PROFILE AGAIN ADDING A BIGGER BID BUT THEY ALL GET CROSSED
![BID PROBLEMS](https://user-images.githubusercontent.com/103065410/166879172-01946a19-a1e3-4de7-b5ef-f84bff5c8ed0.JPG)
![WhatsApp Image 2022-05-05 at 12 28 53 AM](https://user-images.githubusercontent.com/103065410/166879487-404510a3-fbfe-4d88-b90a-6e5aa1820656.jpeg)

![BID PROBLEMS 2](https://user-images.githubusercontent.com/103065410/166879384-ce4ec8ce-9db8-4c7f-ba80-2136634ba570.JPG)

**Comment by asoltys** [comment]
I just tried bidding from my account and was able to. The crossing out can happen when one or more of the inputs to the bid are spent elsewhere on-chain which looks like the case here. The platform is supposed to prevent that from happening though so we need to figure out how sergio's inputs got spent.

**Comment by asoltys** [comment]
Closing for now, can re-open if we see it happen again
