### ISSUE TITLE
CANT upload experiences SHOWSTOPPER

### ISSUE THREAD

**Issue by cozmosnft** [tokenocean/cozmos#23]
I CANT UPLOAD ANYTHING THRES THIS ERROR  BODY REQUEST TOO LARGE OR THE LARGE TEXT..
I HAVE TRIED ANY OF THE 3 METHODS AND WITH 3 DIFFERENT WALLETS.
![error body too large](https://user-images.githubusercontent.com/103065410/167929676-56b5ff17-5f7c-4841-97a4-70a35780e013.JPG)

![SAME SAME](https://user-images.githubusercontent.com/103065410/167929152-68b1ff1a-290e-4d97-ade0-553233fb8213.JPG)
![DEV TOOLS](https://user-images.githubusercontent.com/103065410/167929375-caf0c6dc-990f-4f8e-a243-82aef7894cb9.JPG)

**Comment by asoltys** [comment]
fixed
