### ISSUE TITLE
Description paragraphs wont show on listed experience (-)

### ISSUE THREAD

**Issue by cozmosnft** [tokenocean/cozmos#37]
if you see in the 1st image we are listing the contents of the experience,, and we are using (-) and spaces and different space between lines but when you upload the thing it all squishes together
![WhatsApp Image 2022-05-25 at 1 12 00 PM (1)](https://user-images.githubusercontent.com/103065410/170382385-7107d061-55e8-474a-9cae-c2f91ff43665.jpeg)
![WhatsApp Image 2022-05-25 at 1 12 00 PM (3)](https://user-images.githubusercontent.com/103065410/170382400-1ebf1b58-ad2b-4d02-b210-152d76000da5.jpeg)
![WhatsApp Image 2022-05-25 at 1 12 00 PM (2)](https://user-images.githubusercontent.com/103065410/170382423-520b8af2-4449-4109-80f3-dc681ac275c7.jpeg)

thanks

**Comment by secondl1ght** [comment]
@asoltys should I add markdown support to solve this?
