### ISSUE TITLE
experience transfered Set price option/Creator redeem option

### ISSUE THREAD

**Issue by cozmosnft** [tokenocean/cozmos#4]
We want to see that when transferred or bought an experience, the new owner of the experience can Set a price to it. and then the creator had the Redeem button option.
i have photoshopped how it should be

![set price](https://user-images.githubusercontent.com/103065410/163029769-c0ea8e5e-6475-4eea-ae77-8bb4a8a9b28a.JPG)

![creator only reedems](https://user-images.githubusercontent.com/103065410/163029792-8354235c-8742-475f-b0c8-fe57bdbf0e77.JPG)

.

**Comment by secondl1ght** [comment]
This is complete now, pushing to staging now.
