### ISSUE TITLE
reserve price met, price doesn't change, people don't know what the bid price is at

### ISSUE THREAD

**Issue by cozmosnft** [tokenocean/cozmos#5]
![reserve price hasnt changed](https://user-images.githubusercontent.com/103065410/163037449-29a5e671-ffa8-4f16-acf8-a646a5a9e756.JPG)
we want to see that the reserve price in an auction has been met and it changes once it happens so people can see what the current price is at. i have highlighted the issue and you can see in the history there are bids but in the price up there hasn't

![reserve price hasnt met creator edited](https://user-images.githubusercontent.com/103065410/163037362-d2a173af-63b3-4648-a393-5692890ff174.JPG)
 changed

**Comment by asoltys** [comment]
Fixed
