### ISSUE TITLE
when bid placed and met reserve price, and auction finishes it wont transfer/buy/sell tokens automatically 

### ISSUE THREAD

**Issue by cozmosnft** [tokenocean/cozmos#6]
We want to see that when the reserve price has been met, and the auction is finished, the highest bidder wins the auction.
now the highest bidder wont win it and the owner still has to accept it manually (we see that when the owner has to accept it, he still has to sign 3 times... we might thing the issue is there.)
![bid wont accept automaticly](https://user-images.githubusercontent.com/103065410/163039667-59e2e4cf-a9b2-4a8d-bd93-cc8b06d4041f.JPG)

**Comment by asoltys** [comment]
fixed
