### ISSUE TITLE
history not clear, texts are getting on top of each other plus weird icon sometimes (NOT PRIORITY)

### ISSUE THREAD

**Issue by cozmosnft** [tokenocean/cozmos#7]
we want to see the transaction history clear, not texts are going on top of each other.
YOU CAN TAKE THE WHOLE SCREEN, WE DONT MIND IF YOU HAVE TO DO A FULL SCREEN TO SEE EVERYTHING BETTER.
also there is a weird icon sometimes around there when you sign

![WhatsApp Image 2022-04-12 at 12 47 56 PM](https://user-images.githubusercontent.com/103065410/163042106-7be0a72b-73e0-44f3-b42b-3972369a0dc5.jpeg)
n
![histry](https://user-images.githubusercontent.com/103065410/163042262-e6ee9470-f4be-4f3b-9ea1-9916bf17addb.JPG)

**Comment by secondl1ght** [comment]
This should be fixed now.
