### ISSUE TITLE
cant create new account 

### ISSUE THREAD

**Issue by cozmosnft** [tokenocean/cozmos#8]
i cant create a new account,  i get this error

html> <head><title>502 Bad Gateway</title></head> <body> <center><h1>502 Bad Gateway</h1></center> <hr><center>nginx/1.18.0</center> </body> </html>      <!-- a padding to disable MSIE and Chrome friendly error page --

![error new acc](https://user-images.githubusercontent.com/103065410/165155187-519e8c19-4a09-4547-ad6f-a736e88c6a27.JPG)
>

**Comment by improvethings** [comment]
![Screenshot from 2022-04-25 17-00-22](https://user-images.githubusercontent.com/16601027/165193363-2baa4d0a-23c5-4b56-8c40-6670845cebea.png)

browser console logs attached

**Comment by asoltys** [comment]
fixed, the backend app container was down for some reason, had to restart it
