### ISSUE TITLE
SHOW STOPPER bug at log in.

### ISSUE THREAD

**Issue by cozmosnft** [tokenocean/cozmos#9]
i created acc doing sig up, and then it asks me to log in but it fails to do it. i get (failed to log in) and wont log i
![bug log in](https://user-images.githubusercontent.com/103065410/165620738-a6fba9a4-40b3-4817-887c-24e878cd0728.JPG)
n

**Comment by asoltys** [comment]
Need to make sure you check your email to activate the account. We could improve the 'Login failed' message to be more helpful if the failure is from the account not being activated.

**Comment by secondl1ght** [comment]
Also I believe there is an improved error message now.
